=== christian-schlichtherle/trueupdate/src/site/resources/xml/ns/config/server-1.0.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
  - Copyright (C) 2013 Schlichtherle IT Services & Stimulus Software.
  - All rights reserved. Use is subject to license terms.
  -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="https://trueupdate.java.net/xml/ns/config"
           elementFormDefault="qualified"
           targetNamespace="https://trueupdate.java.net/xml/ns/config"
           version="1.0">

  <xs:element name="server" type="tns:MavenUpdateServerParameters"/>

  <xs:complexType name="MavenUpdateServerParameters">
    <xs:sequence>
      <xs:element name="repositories" type="tns:MavenParameters"/>
    </xs:sequence>
    <xs:attribute name="version" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="MavenParameters">
    <xs:sequence>
      <xs:element name="local" type="tns:LocalRepository"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="remote" type="tns:RemoteRepository"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="LocalRepository">
    <xs:all>
      <xs:element minOccurs="0" name="type" type="xs:string"/>
      <xs:element name="basedir" type="xs:string"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="RemoteRepository">
    <xs:all>
      <xs:element minOccurs="0" name="url" type="xs:string"/>
      <xs:element minOccurs="0" name="type" type="xs:string"/>
      <xs:element minOccurs="0" name="id" type="xs:string"/>
    </xs:all>
  </xs:complexType>
</xs:schema>

=== christian-schlichtherle/trueupdate/trueupdate-server/trueupdate-server-maven/src/test/filtered/update/server.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  - Copyright (C) 2013 Schlichtherle IT Services & Stimulus Software.
  - All rights reserved. Use is subject to license terms.
  -->
<server
    xmlns="https://trueupdate.java.net/xml/ns/config"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://trueupdate.java.net/xml/ns/config
                        https://trueupdate.java.net/xml/ns/config/server-1.0.xsd"
    version="1.0">
    <repositories>
        <!-- Configures the mandatory local repository. -->
        <local>
            <directory>${user.home}/.m2/repository</directory>
            <!-- The optional type. -->
            <type/>
        </local>
        <!--
          - Configures an optional remote repository.
          - Specify one element per repository.
          -->
        <remote>
            <!-- The optional ID. -->
            <id>central</id>
            <!-- The optional type. -->
            <type>default</type>
            <url>http://repo1.maven.org/maven2/</url>
        </remote>
    </repositories>
</server>
