=== christian-schlichtherle/trueupdate/src/site/resources/xml/ns/config-1.0.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
- Copyright (C) 2013 Schlichtherle IT Services & Stimulus Software.
- All rights reserved. Use is subject to license terms.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="https://trueupdate.java.net/xml/ns/config"
           elementFormDefault="qualified"
           targetNamespace="https://trueupdate.java.net/xml/ns/config"
           version="1.0">

    <xs:element name="agent" type="JmsUpdateAgentParameters">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Configures the update agent.
            </xs:documentation>
        </xs:annotation>
    </xs:element>

    <xs:element name="manager" type="JmsUpdateManagerParameters">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Configures the update manager.
            </xs:documentation>
        </xs:annotation>
    </xs:element>

    <xs:element name="server" type="MavenUpdateServerParameters">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Configures the update server.
            </xs:documentation>
        </xs:annotation>
    </xs:element>

    <xs:complexType name="JmsUpdateAgentParameters">
        <xs:all>
            <xs:element name="application" type="ApplicationParameters">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        Configures the client application.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="subscriptionTimer" type="TimerParameters">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        The optional timer parameters for the initial delay for
                        the subscription to the update manager.
                        Configuring this delay may help to avoid an illegal
                        state in the client application at startup if there is
                        an update available immediately.
                        Note that the period child element will be ignored in
                        this context.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="messaging" type="JmsParameters">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        Configures messaging parameters for use with JMS.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:all>
        <xs:attribute name="version" type="xs:string" use="required" fixed="1.0"/>
    </xs:complexType>

    <xs:complexType name="JmsUpdateManagerParameters">
        <xs:all>
            <xs:element name="updateService" type="UpdateServiceParameters">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        The update service parameters.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="updateTimer" type="TimerParameters">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        The timer parameters for checking for artifact updates.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="messaging" type="JmsParameters">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        Configures messaging parameters for use with JMS.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:all>
        <xs:attribute name="version" type="xs:string" use="required" fixed="1.0"/>
    </xs:complexType>

    <xs:complexType name="UpdateServiceParameters">
        <xs:all>
            <xs:element name="uri" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        The base URI of the update service.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="TimerParameters">
        <xs:all>
            <xs:element default="0" minOccurs="0" name="delay" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        The initial delay of the timer.
                        The default value is 0.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element default="0" minOccurs="0" name="period" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        The period of the timer.
                        The default value is 0.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="unit" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        The time unit.
                        This element is optional if and only if the values of
                        the delay and the period elements are zero.
                        Valid values are seconds, minutes, hours or days.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="JmsParameters">
        <xs:all>
            <xs:element minOccurs="0" name="naming" type="JndiParameters">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        Configures optional naming parameters for use with JNDI.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="connectionFactory" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        The JNDI name of the JMS connection factory.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="from" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        The JNDI name of the JMS destination for the sender.
                        When configuring the update agent, this property refers
                        to the JMS destination for the update agent, e.g.
                        "AutoUpdate/Agent".
                        Likewise, when configuring the update manager, this
                        property refers to the JMS destination for the update
                        manager, e.g. "AutoUpdate/Manager".
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="to" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        The JNDI name of the JMS destination for the recipient.
                        When configuring the update agent, this property refers
                        to the JMS destination for the update manager, e.g.
                        "AutoUpdate/Manager".
                        When configuring the update manager, this property is
                        optional and ignored.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="JndiParameters">
        <xs:all>
            <xs:element default="javax.naming.InitialContext" minOccurs="0" name="initialContextClass" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        The class name of the initial context.
                        The default value is "javax.naming.InitialContext".
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="contextLookup" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        The optional JNDI name of a context to lookup.
                        This should be specified if and only if the JMS
                        administered objects (connection factory and
                        destinations) need to get looked up from a context
                        other than the initial context.
                        The property value then needs to specify the JNDI name
                        of the context to lookup from the initial context,
                        e.g. "java:comp/env".
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="MavenUpdateServerParameters">
        <xs:sequence>
            <xs:element name="repositories" type="MavenParameters">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        Configures Maven parameters.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="version" type="xs:string" use="required" fixed="1.0"/>
    </xs:complexType>

    <xs:complexType name="ApplicationParameters">
        <xs:all>
            <xs:element name="artifact" type="ArtifactDescriptor">
                <xs:annotation>
                    <xs:documentation>
                        The Maven coordinates for the client application.
                        See http://maven.apache.org/pom.html#Maven_Coordinates .
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="location" type="xs:string">
                <xs:annotation>
                    <xs:documentation>
                        The current location of the client application.
                        The syntax for this string is defined by the
                        TrueUpdate Installer component which is used by the
                        update manager.
                        With the TrueUpdate Installer Tomcat, this is the
                        context path of the application, e.g. "/myapp".
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="updateLocation" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        The optional update location of the client application.
                        Like the current location, the syntax for this string
                        is defined by the TrueUpdate Installer component.
                        If not specified the application is updated in place,
                        which is the current location.
                        Note that this property may not be supported by all
                        TrueUpdate Installer components.
                        The component TrueUpdate Installer Tomcat does support
                        this property, however.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element default="net.java.trueupdate.agent.spec.UpdateAgentListener" name="listenerClass" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        The name of the listener class for the client
                        application.
                        The class must be public, have a public no-argument
                        constructor and extend the class
                        net.java.trueupdate.agent.spec.UpdateAgentListener or
                        be the same class.
                        If not named, the default value is
                        "net.java.trueupdate.agent.spec.UpdateAgentListener".
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="ArtifactDescriptor">
        <xs:all>
            <xs:element name="groupId" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        The group identifier.
                        The syntax for this string is defined by Maven.
                        See http://maven.apache.org/pom.html#Maven_Coordinates .
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="artifactId" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        The artifact identifier.
                        The syntax for this string is defined by Maven.
                        See http://maven.apache.org/pom.html#Maven_Coordinates .
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="version" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        The version.
                        The syntax for this string is defined by Maven.
                        See http://maven.apache.org/pom.html#Maven_Coordinates .
                        Note that the update manager does only a simple test
                        for equality using String.equals() to detect if the
                        client application needs to get updated.
                        As a result, if you specify a snapshot version here
                        (e.g. 0.1-SNAPSHOT), then the update manager will
                        update the client application to this snapshot version
                        once and will not update the client application to a
                        newer build unless the version string changes.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="classifier" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        The optional classifier.
                        The syntax for this string is defined by Maven.
                        See http://maven.apache.org/pom.html#Maven_Coordinates .
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element default="jar" minOccurs="0" name="extension" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        The optional extension.
                        The syntax for this string is defined by Maven.
                        See http://maven.apache.org/pom.html#Maven_Coordinates .
                        The default value is "jar".
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="MavenParameters">
        <xs:sequence>
            <xs:element name="local" type="LocalRepository">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        Configures the local Maven repository.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="remote" type="RemoteRepository">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        Configures an optional remote Maven repository.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="LocalRepository">
        <xs:all>
            <xs:element default="${user.home}/.m2" minOccurs="0" name="directory" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        The optional base directory of the local Maven repository.
                        The default value is "${user.home}/.m2".
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="type" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        The optional repository type.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="RemoteRepository">
        <xs:all>
            <xs:element default="http://repo1.maven.org/maven2/" minOccurs="0" name="url" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        The optional repository URL.
                        The default value is "http://repo1.maven.org/maven2/",
                        which is the Maven Central URL.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="id" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        The optional repository identifier.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="type" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        The optional repository type.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:all>
    </xs:complexType>
</xs:schema>

=== christian-schlichtherle/trueupdate/trueupdate-archetype/trueupdate-archetype-glassfish/src/main/resources/archetype-resources/autoupdate-demo-config/src/main/filtered/update/agent.xml
#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
<?xml version="1.0" encoding="UTF-8"?>
<agent xmlns="https://trueupdate.java.net/xml/ns/config"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="https://trueupdate.java.net/xml/ns/config
                           https://trueupdate.java.net/xml/ns/config-1.0.xsd"
       version="1.0">
    <application>
        <artifact>
            <groupId>${symbol_dollar}{project.groupId}</groupId>
            <artifactId>${symbol_dollar}{project.artifactId}</artifactId>
            <version>${symbol_dollar}{project.version}</version>
            <extension>${symbol_dollar}{project.packaging}</extension>
        </artifact>
        <location>/${parentArtifactId}-demo</location>
        <listenerClass>${package}.demo.ApplicationListener</listenerClass>
    </application>
    <subscriptionTimer>
        <delay>${symbol_dollar}{agent.subscriptionTimer.delay}</delay>
        <unit>seconds</unit>
    </subscriptionTimer>
    <messaging>
        <connectionFactory>${parentArtifactId}/connection-factory</connectionFactory>
        <from>${parentArtifactId}/agent</from>
        <to>${parentArtifactId}/manager</to>
    </messaging>
</agent>

=== christian-schlichtherle/trueupdate/trueupdate-archetype/trueupdate-archetype-tomcat/src/main/resources/archetype-resources/autoupdate-manager/src/main/filtered/update/manager.xml
#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
<?xml version="1.0" encoding="UTF-8"?>
<manager xmlns="https://trueupdate.java.net/xml/ns/config"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://trueupdate.java.net/xml/ns/config https://trueupdate.java.net/xml/ns/config-1.0.xsd"
         version="1.0">
    <updateService>
        <uri>${symbol_dollar}{manager.updateService.uri}</uri>
    </updateService>
    <updateTimer>
        <period>${symbol_dollar}{manager.updateTimer.period}</period>
        <unit>minutes</unit>
    </updateTimer>
    <messaging>
        <connectionFactory>${parentArtifactId}/connection-factory</connectionFactory>
        <from>${parentArtifactId}/manager</from>
    </messaging>
</manager>

=== christian-schlichtherle/trueupdate/trueupdate-archetype/trueupdate-archetype-glassfish/src/main/resources/archetype-resources/update-agent-config/src/main/filtered/update/agent.xml
#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
<?xml version="1.0" encoding="UTF-8"?>
<agent
    xmlns="https://trueupdate.java.net/xml/ns/config"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://trueupdate.java.net/xml/ns/config
                        https://trueupdate.java.net/xml/ns/config-1.0.xsd"
       version="1.0">
    <application>
        <artifact>
            <groupId>${symbol_dollar}{project.groupId}</groupId>
            <artifactId>${application}</artifactId>
            <version>${symbol_dollar}{project.version}</version>
            <extension>ear</extension>
        </artifact>
        <location>ear://${symbol_dollar}{basedir}/../application/target/${application}-${project.version}.ear?moduleID=${application}&amp;username=admin&amp;uri=deployer:Sun:AppServer::localhost:4848</location>
        <listenerClass>${package}.ApplicationListener</listenerClass>
    </application>
    <subscriptionTimer>
        <delay>${symbol_dollar}{agent.subscriptionTimer.delay.seconds}</delay>
        <unit>seconds</unit>
    </subscriptionTimer>
    <messaging>
        <connectionFactory>update/connection-factory</connectionFactory>
        <from>update/agent</from>
        <to>update/manager</to>
    </messaging>
</agent>
